// Writes docs/<Name>.md — the per-component reference the design agent gets as <Name>.prompt.md.
// Frontmatter `category` decides the component's group in the design pane.
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const here = path.dirname(url.fileURLToPath(import.meta.url));
const OUT = path.resolve(here, '../docs');

const DOCS = [
  ['Icon', 'Icons', 'A single glyph from the site\'s own icon set, inlined as SVG so it needs no asset origin.',
    `<Icon name="compass" size={18} title="Four Noble Truths" />`,
    'Names come from the app\'s shipped set: `compass`, `gear`, `question`, `book`, `star`, `moon`, `sun`, `play`, `memo`, `copy`, `eye`, and 30 more. File names are camel-cased: `open-link.svg` is `openLink`.\n\nTwo things to know before picking one. Most glyphs hard-code `fill="#989898"`, which beats the `currentColor` on the `<svg>` — they read grey on any ground, light or dark, which is how the app looks too. Only `select`, `memo`, `play`, `tableColumns`, `linkSolidFull` and `codeCompareSolidFull` follow `currentColor`. And `homeIcon` is unusable at normal sizes: its artwork occupies roughly the top-left 3% of its viewBox, so it renders as near-nothing — reach for `tableColumns` instead.\n\nThe set has no envelope and no brand marks; the app pulls those from Font Awesome at runtime.'],
  ['Brand', 'Shell', 'The dhamma.gift signboard — logo plus wordmark, and the page\'s primary way home.',
    `<Brand />\n<Brand variant="mark" />`,
    'Shown only on the home state. In results and reader the signboard is gone and the conch alone lives inside the search field — pass `variant="mark"` for that one.'],
  ['IconButton', 'Shell', 'A chrome button that is nothing but its icon — burger, back, close.',
    `<IconButton label="Menu" variant="menu">\n  <Icon name="listUlSolidFull" size={19} />\n</IconButton>`,
    '`label` is required: these buttons carry no visible text. Use `variant="plain"` inside `ReaderHero`, where the pill border would compete with the text.'],
  ['SearchShell', 'Shell', 'The signature search field: one glass shell holding the home link, the query input, a clear button, the quick-settings dot and the submit magnifier.',
    `<SearchShell placeholder="kacchapa" />\n<SearchShell value="satipa" showClear busy />`,
    'This is the same element in every state — home, results, reader — which is why typed text and focus survive navigation. On the home screen the signboard shows above it, so pass `showLogo={false}` there.'],
  ['Toolbar', 'Shell', 'The row of light pills above the results table and inside the reader.',
    `<Toolbar>\n  <ToolbarButton label="Theme"><Icon name="circleHalfStroke" /></ToolbarButton>\n  <ToolbarButton label="Dictionary"><Icon name="comment" /></ToolbarButton>\n  <ToolbarButton label="Read marks" pressed><Icon name="solidStar" /></ToolbarButton>\n</Toolbar>`,
    'Sticky toggles (read marks, column mode) carry `pressed`; one-shot actions leave it unset.'],
  ['ToolbarButton', 'Shell', 'One button in the results/reader toolbar — Bootstrap\'s light pill, as shipped.',
    `<ToolbarButton label="Expand all">Expand</ToolbarButton>`,
    'Takes a glyph or a short word. Set `pressed` for toggles so the state is announced, not just drawn.'],
  ['BusyIndicator', 'Shell', 'The page-level spinner parked over the results area while a search or a sutta is in flight.',
    `<BusyIndicator label="Searching…" />`,
    'Announced politely — it never steals focus from the query field.'],
  ['Tile', 'Home', 'One home-screen shortcut: a glyph in an accent disc with a caption under it.',
    `<Tile label="Dīgha Nikāya" icon={<Icon name="book" size={20} />} description="34 long discourses" />`,
    'Always a button, never a link — browsers start their own drag on anchors, which would fight tile reordering. Tiles are user-reorderable and hideable in the app.'],
  ['TileGrid', 'Home', 'The home screen\'s grid of shortcuts.',
    `<TileGrid>\n  <Tile label="Suttas" icon={<Icon name="book" size={20} />} />\n  <Tile label="Vinaya" icon={<Icon name="dharmachakra" size={20} />} />\n</TileGrid>`,
    'Lay tiles out here rather than in a bespoke grid — the spacing and wrap behaviour are part of the home screen\'s identity.'],
  ['Segmented', 'Home', 'The small segmented switch used for language and theme in the drawer\'s settings group.',
    `<Segmented\n  value="ru"\n  options={[{ value: 'ru', label: 'Русский' }, { value: 'en', label: 'English' }]}\n/>`,
    'Selection is carried by `aria-pressed` on the buttons, not by a class. Best for two or three options; more than that belongs in a `Sheet`.'],
  ['ScopeSummary', 'Home', 'Spells out which books a search actually covered, grouped the way the canon is.',
    `<ScopeSummary groups={[\n  { title: '4 Nikāyas', books: ['Dīgha', 'Majjhima', 'Saṁyutta', 'Aṅguttara'] },\n  { title: 'Khuddaka', books: ['Dhammapada', 'Udāna', 'Itivuttaka'] },\n]} />`,
    'The results header shows a short label ("4 Nikāyas + 6 KN"); this is the expansion behind it, so a reader can tell what was not searched.'],
  ['PaliQuote', 'Home', 'A canonical quotation set as a block: Pali line, translation, references, and an optional caveat.',
    `<PaliQuote\n  pali="Sabbe saṅkhārā aniccā"\n  translation="All conditioned things are impermanent."\n  refs={<a href="/dhp277">Dhp 277</a>}\n/>`,
    'The Pali line is marked `lang="pi"`, which is what gives it the serif face and the dictionary lookup.'],
  ['AnnounceBox', 'Home', 'The site-wide notice band on the home screen — one short message, dismissible.',
    `<AnnounceBox>New: Devanagari reading mode</AnnounceBox>`,
    'Announced as a status, so it never steals focus. Keep it to one line: it sits in a band across the whole screen.'],
  ['CtaButton', 'Home', 'An app-store style badge in the home screen\'s "get the app" row.',
    `<CtaButton title="Get it on Google Play" href="https://play.google.com/…">\n  <img src="/assets/img/buttons/google-play.png" alt="Google Play" />\n</CtaButton>`,
    'Artwork carries the whole button, so `title` is the only text an assistive reader gets — write it as the action, not the vendor.'],
  ['ContactButton', 'Home', 'One round icon link in the home screen\'s contacts row.',
    `<ContactButton title="Telegram" href="https://t.me/dhammagift">\n  <Icon name="comment" />\n</ContactButton>`,
    'Mail links stay in the tab; everything else opens in a new one.'],
  ['Sheet', 'Overlays', 'The bottom sheet a home tile opens — drag handle, title, optional tabs, and a body of rows.',
    `<Sheet title="Dīgha Nikāya" tabs={[{ id: 'all', label: 'All' }, { id: 'starred', label: 'Starred' }]} activeTab="all">\n  <SheetRow label="DN 22" description="Mahāsatipaṭṭhāna" starred />\n  <SheetRow label="DN 16" description="Mahāparinibbāna" />\n</Sheet>`,
    'Rises from the bottom edge on phones; above 768px the same markup is centred as a panel. Use `MegaMenu` instead when the panel should stay anchored to the tile that opened it.'],
  ['SheetRow', 'Overlays', 'One entry inside a Sheet — a link with an optional description, or a compact chip.',
    `<SheetRow label="MN 10" description="Satipaṭṭhāna Sutta" />\n<SheetRow label="Gemini" chip />`,
    'The star sits at the leading edge, in the ordinary glyph\'s place: pushed to the end of the row it reads as a separate button rather than a mark on the item. Chips are for short self-evident labels.'],
  ['Drawer', 'Overlays', 'The slide-in navigation drawer behind the burger — navigation first, then settings.',
    `<Drawer>\n  <DrawerGroup title="Navigation">\n    <DrawerRow href="/" icon={<Icon name="homeIcon" />}>Home</DrawerRow>\n    <DrawerRow icon={<Icon name="compass" />}>Four Noble Truths</DrawerRow>\n  </DrawerGroup>\n  <DrawerGroup title="Settings" collapsible={false}>\n    <Segmented value="ru" options={[{ value: 'ru', label: 'RU' }, { value: 'en', label: 'EN' }]} />\n  </DrawerGroup>\n</Drawer>`,
    'This replaced a Bootstrap dropdown — the drawer is what makes the page read as an app rather than a website menu.'],
  ['DrawerRow', 'Overlays', 'One line in the Drawer — a glyph and a label, linking somewhere or running an action.',
    `<DrawerRow href="/settings/" icon={<Icon name="gear" />}>Settings</DrawerRow>`,
    'Keep labels to one or two words; the drawer is scanned, not read.'],
  ['DrawerGroup', 'Overlays', 'A titled section of the Drawer.',
    `<DrawerGroup title="Navigation" open>\n  <DrawerRow>Links</DrawerRow>\n</DrawerGroup>\n<DrawerGroup title="Settings" collapsible={false}>…</DrawerGroup>`,
    'Collapsible groups are a native `<details>` — no script, and they work before any JS runs. Pass `collapsible={false}` for a plain heading.'],
  ['ToggleRow', 'Overlays', 'A settings switch: label on the left, sliding toggle on the right.',
    `<ToggleRow label="Show variants" hotkey="Alt+V" on />\n<ToggleRow label="Two columns" hotkey="Alt+C" />`,
    'When a setting also answers to a keyboard shortcut, spell it out here — otherwise nobody discovers it.'],
  ['MegaMenu', 'Overlays', 'The anchored panel a home tile opens on wide screens — the same sheet shell, pinned to its tile instead of rising from the bottom.',
    `<MegaMenu title="External sources">\n  <MegaMenuGroup title="Editions">\n    <SheetRow label="SuttaCentral" />\n    <SheetRow label="Buddha Jayanthi" />\n  </MegaMenuGroup>\n  <MegaMenuGroup title="AI" layout="chips" divider>\n    <SheetRow label="Gemini" chip />\n    <SheetRow label="DeepSeek" chip />\n  </MegaMenuGroup>\n</MegaMenu>`,
    'Closes on Escape and on backdrop click. Pass `compact` when the panel holds many short entries.'],
  ['MegaMenuGroup', 'Overlays', 'One titled cluster inside a MegaMenu.',
    `<MegaMenuGroup title="Translators" layout="chips">\n  <SheetRow label="Sujato" chip />\n  <SheetRow label="Thanissaro" chip />\n</MegaMenuGroup>`,
    'Sets whose labels speak for themselves — model names, edition codes — use the chip layout: four names like "Gemini" do not earn four full-width rows.'],
  ['ResultsTable', 'Results', 'The search results table — an index of suttas first, a list of hits second.',
    `<ResultsTable>\n  <ResultRow suttaId="dn22" paliTitle="Mahāsatipaṭṭhānasutta" translatedTitle="Большое наставление о способах установления памятования" />\n</ResultsTable>`,
    'Rows expand in place to reveal the matching segments, so keep the row itself to identity and provenance.'],
  ['ResultRow', 'Results', 'One sutta in the results table: its id, both titles, the words that matched, and where else the text can be read.',
    `<ResultRow\n  suttaId="sn56.11"\n  paliTitle="Dhammacakkappavattanasutta"\n  translatedTitle="Setting the Wheel of Dhamma Rolling"\n  titleLang="en"\n  matchedWords={<>kacchapa, <Match>kacchapānaṁ</Match></>}\n  readMark read\n/>`,
    'Titles come as a pair on purpose — the Pali is the stable identity, the translated title is what a reader recognizes. Show the inflected forms grep actually matched, not just the query.'],
  ['QuoteSegment', 'Results', 'One canonical segment as the results render it: the Pali line, its variant reading, and every translation stacked in the right column.',
    `<QuoteSegment\n  id="sn56.11:2.1"\n  pali={<>Dveme, bhikkhave, antā pabbajitena na sevitabbā.</>}\n  translations={[{ lang: 'ru', text: 'Монахи, эти две крайности не должны practiced.', translator: 'ru_o' }]}\n/>`,
    'Pass `context` for the lines shown around a hit — it emits the same Bootstrap utilities the results view emits (`opacity-90` on the Pali, `text-muted opacity-75` on the translations). Only the translation side actually dims: `opacity-90` and `font-weight-light` are Bootstrap 4 names the app kept through its Bootstrap 5 upgrade, and neither resolves to a rule. The component reproduces them rather than silently correcting the app.\n\nSegment ids are the addressing scheme end to end — the same `sn56.11:2.1` is the anchor, the copy-link target and the reader\'s scroll destination.'],
  ['Match', 'Results', 'A search hit inside a line.',
    `<>Atha kho so <Match>kacchapo</Match> …</>`,
    'The results view wraps every occurrence in one of these, including the inflected forms grep found — which is why a search for `kacchapa` highlights `kacchapānaṁ` too.'],
  ['ExternalLinks', 'Results', 'The row of third-party source links a sutta carries.',
    `<ExternalLinks links={[\n  { label: 'Voice', title: 'Text-to-Speech' },\n  { label: 'SC', href: 'https://suttacentral.net/dn22', title: 'SuttaCentral.net' },\n  { label: 'BJT', href: '#', title: 'Buddha Jayanthi' },\n]} />`,
    'Order is fixed and matches the legacy reader, so the same sutta reads the same on both. Every link is marked `sc-ext-link`, which is how features like PDF export find them all.'],
  ['ReaderHero', 'Reader', 'The reader\'s own header row: the way home, a search field, and the borderless icon buttons beside it.',
    `<ReaderHero query="dn22">\n  <IconButton label="Contents" variant="plain"><Icon name="listUlSolidFull" size={18} /></IconButton>\n  <IconButton label="Settings" variant="plain"><Icon name="gear" size={18} /></IconButton>\n</ReaderHero>`,
    'Buttons here drop their pill: on this row the glyph alone reads better than a border around it.'],
  ['ReaderSegment', 'Reader', 'One segment as the reader lays it out: Pali on the left, every translation stacked in the right column.',
    `<ReaderSegment\n  id="dn22:1.1"\n  pali="Evaṁ me sutaṁ—"\n  variant="evaṁ me sutaṁ (bj)"\n  translations={[\n    { lang: 'ru', text: 'Так я слышал.', translator: 'ru_o' },\n    { lang: 'en', text: 'So I have heard.', translator: 'en_sujato' },\n  ]}\n/>`,
    'The same markup serves every mode — single, two translators, two languages. What changes is which columns get filled, never the structure, which is why switching mode keeps your place in the text.'],
  ['ModeSwitchPanel', 'Reader', 'The reader\'s mode list — one row per way of laying a sutta out.',
    `<ModeSwitchPanel\n  active="single"\n  modes={[\n    { id: 'single', label: 'Single', description: 'One translation beside the Pali', hotkey: '1' },\n    { id: 'multiTran', label: 'Multi Translators', description: 'Two translators, same language', hotkey: '2' },\n    { id: 'multiLang', label: 'Multi Language', description: 'Russian and English side by side', hotkey: '3' },\n  ]}\n/>`,
    'Modes come from `configs/reader/mode-table.json`, which the server and the client both read; the order of keys there is the order of rows here.'],
  ['TocItem', 'Reader', 'One line of a sutta\'s table of contents.',
    `<TocItem level="h1" pali="Uddesa" translated="Изложение" />\n<TocItem level="h3" pali="Kāyānupassanā" translated="Созерцание тела" />`,
    'Both scripts sit in the same row and each is separately clickable, so tapping either scrolls to the same place — the reader\'s language toggle then decides which is visible.\n\n`lang` takes the reader\'s **three-letter** codes here — `rus`, `eng`, `tha` — not the two-letter codes `ReaderSegment` and `QuoteSegment` use. The TOC styles are written as `.toc-item .rus-lang, .toc-item .eng-lang`, so `ru` renders unstyled. Default is `rus`.'],
  ['SmartButton', 'Reader', 'One control in the reader\'s floating smart panel.',
    `<SmartButton label="Variants"><Icon name="eye" size={18} /></SmartButton>`,
    'Each button shortcuts a control that also lives in the toolbar; the panel exists so the common few are reachable without leaving the text.'],
];

for (const [name, category, summary, example, notes] of DOCS) {
  const body = `---\ncategory: ${category}\n---\n\n# ${name}\n\n${summary}\n\n\`\`\`jsx\n${example}\n\`\`\`\n\n${notes}\n`;
  fs.writeFileSync(path.join(OUT, `${name}.md`), body);
}
console.log(`docs: ${DOCS.length} files -> docs/`);
