// Generates src/icons/generated.ts from the app's real shipped SVG set
// (public/overrides/svg — served at /assets/svg/* in production).
// The design system inlines this artwork so components are self-contained:
// a preview card or a generated design has no /assets URL to resolve.
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const here = path.dirname(url.fileURLToPath(import.meta.url));
const SVG_DIR = path.resolve(here, '../../public/overrides/svg');
const OUT = path.resolve(here, '../src/icons/generated.ts');

const camel = (s) => s.replace(/[-_](.)/g, (_, c) => c.toUpperCase());

const entries = [];
for (const file of fs.readdirSync(SVG_DIR).sort()) {
  if (!file.endsWith('.svg')) continue;
  const raw = fs.readFileSync(path.join(SVG_DIR, file), 'utf8');
  const open = raw.match(/<svg\b[^>]*>/i);
  if (!open) continue;
  const viewBox = (open[0].match(/viewBox=["']([^"']+)["']/i) || [, '0 0 512 512'])[1];
  const inner = raw
    .slice(open.index + open[0].length, raw.lastIndexOf('</svg>'))
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/\s+/g, ' ')
    .trim();
  entries.push({ name: camel(file.replace(/\.svg$/, '')), viewBox, inner });
}

// Brand artwork — the same two images the app serves from /assets/img. Inlined as data URIs
// for the same reason as the glyphs: a design built with this library has no dhamma.gift
// origin to fetch them from.
const IMG_DIR = path.resolve(here, '../../public/overrides/img');
const dataUri = (file) =>
  'data:image/png;base64,' + fs.readFileSync(path.join(IMG_DIR, file)).toString('base64');
const brand = {
  mark: dataUri('dgsankhaonly.png'),   // the shell/conch alone (in-field logo)
  full: dataUri('dgsanhkalogo.png'),   // full signboard logo (home hero)
};

const body = entries
  .map((e) => `  ${JSON.stringify(e.name)}: { viewBox: ${JSON.stringify(e.viewBox)}, path: ${JSON.stringify(e.inner)} },`)
  .join('\n');

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(
  OUT,
  `// GENERATED by scripts/gen-icons.mjs from public/overrides/svg — do not edit by hand.\n` +
    `export interface IconGlyph {\n  viewBox: string;\n  path: string;\n}\n\n` +
    `export const glyphs = {\n${body}\n} as const;\n\n` +
    `export type IconName = keyof typeof glyphs;\n\n` +
    `/** Brand artwork from public/overrides/img, inlined as data URIs. */\n` +
    `export const brandArt = {\n` +
    `  mark: ${JSON.stringify(brand.mark)},\n` +
    `  full: ${JSON.stringify(brand.full)},\n` +
    `} as const;\n`
);
console.log(`icons: ${entries.length} glyphs -> src/icons/generated.ts`);
