#!/usr/bin/env node
// Disk guard for the checks in this repo.
//
// Why it exists: a handful of browser profiles, each holding a downloaded 509MB offline library,
// filled a 49GB disk to 100% while the Capacitor work was going on. Nothing warned, nothing cleaned
// up, and the first symptom was a failed write in an unrelated command — on a server that also runs
// production. Tests and builds may use disk; they must not use ALL of it, and nobody should have to
// notice by hand.
//
// What it does, in order:
//   1. measures free space on the filesystem that holds this repo;
//   2. if free is below WARN_MB (default 6000), deletes ONLY throwaway artifacts this repo creates —
//      browser profiles from the app-ui suite and the old dg-app-full e2e profiles, plus leftover
//      download zips under /tmp. Never project data (dg.db, siteroot/mobile-data, www, android/…);
//   3. logs what it freed, and if free is still below CRIT_MB (default 2000) writes a loud line and
//      POSTs to DG_ALERT_WEBHOOK when that is configured (a JSON body, so any bot/webhook accepts it);
//   4. exits non-zero only in the critical case, so cron mailers/pm2 alerting can pick it up.
//
// Usage:
//   node scripts/disk-guard.js            # one pass (this is what cron/pm2 should call)
//   node scripts/disk-guard.js --watch    # keep checking every DG_GUARD_INTERVAL seconds (default 300)
//
// Suggested cron (every 10 minutes, one line): see the README section this script prints with --help.
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const WARN_MB = +(process.env.DG_GUARD_WARN_MB || 6000);
const CRIT_MB = +(process.env.DG_GUARD_CRIT_MB || 2000);
const LOG = process.env.DG_GUARD_LOG || path.join(ROOT, 'test', '.disk-guard.log');

// Only paths this repo's tooling creates, and only ones that can be regenerated by running it again.
// Deliberately NOT here: dg.db, siteroot/mobile-data (the published artifact), www/, android/.
const THROWABLE = [
    path.join(ROOT, 'test', '.app-ui-profiles'),
    ...fs.existsSync(path.join(ROOT, 'dg-app-full'))
        ? fs.readdirSync(path.join(ROOT, 'dg-app-full'))
            .filter(n => n.startsWith('.e2e-profile'))
            .map(n => path.join(ROOT, 'dg-app-full', n))
        : [],
    path.join(ROOT, 'dg-app-full', '.e2e-profile'),
];

// Leftover SDK/gradle download archives: pure caches, re-downloaded on demand.
const THROWABLE_TMP = [
    '/tmp/sdkdl',
    '/tmp/android-cmdline',
    '/tmp/cmdline-tools.zip',
];

function freeMb() {
    try {
        const st = fs.statfsSync(path.parse(ROOT).root);
        return Math.round((st.bavail * st.bsize) / (1024 * 1024));
    } catch (e) {
        return null;
    }
}

function dirSizeMb(p) {
    let total = 0;
    const walk = (dir) => {
        let entries;
        try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch (e) { return; }
        for (const e of entries) {
            const full = path.join(dir, e.name);
            try {
                if (e.isDirectory()) walk(full);
                else total += fs.statSync(full).size;
            } catch (err) { /* vanished mid-walk */ }
        }
    };
    walk(p);
    return Math.round(total / (1024 * 1024));
}

function log(line) {
    const stamped = `${new Date().toISOString()} ${line}`;
    console.log(stamped);
    try { fs.appendFileSync(LOG, stamped + '\n'); } catch (e) { /* logging must never break the guard */ }
}

async function alert(message) {
    log('ALERT: ' + message);
    const hook = process.env.DG_ALERT_WEBHOOK;
    if (!hook) return;
    try {
        await fetch(hook, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ text: message, host: require('os').hostname(), free_mb: freeMb() }),
        });
    } catch (e) {
        log('alert webhook failed: ' + e.message);
    }
}

function clean() {
    let freed = 0;
    for (const p of [...THROWABLE, ...THROWABLE_TMP]) {
        if (!fs.existsSync(p)) continue;
        const mb = fs.statSync(p).isDirectory() ? dirSizeMb(p) : Math.round(fs.statSync(p).size / (1024 * 1024));
        try {
            fs.rmSync(p, { recursive: true, force: true });
            freed += mb;
            log(`removed ${p} (${mb}MB)`);
        } catch (e) {
            log(`could not remove ${p}: ${e.message}`);
        }
    }
    return freed;
}

async function pass() {
    const before = freeMb();
    if (before === null) { log('cannot read free space; nothing to do'); return 0; }
    if (before >= WARN_MB) { log(`ok: ${before}MB free (warn below ${WARN_MB}MB)`); return 0; }

    log(`low disk: ${before}MB free — cleaning throwaway test artifacts`);
    const freed = clean();
    const after = freeMb();
    log(`cleaned ${freed}MB; ${after}MB free now`);

    if (after !== null && after < CRIT_MB) {
        await alert(`Dhamma.gift server: only ${after}MB free on ${path.parse(ROOT).root} ` +
            `(cleaned ${freed}MB of test artifacts and it was not enough). ` +
            `Check for a runaway build/download.`);
        return 1;
    }
    return 0;
}

(async () => {
    if (process.argv.includes('--help')) {
        console.log(fs.readFileSync(__filename, 'utf8').split('Usage:')[1].split('const fs =')[0]);
        return;
    }
    if (!process.argv.includes('--watch')) {
        process.exit(await pass());
    }
    const interval = +(process.env.DG_GUARD_INTERVAL || 300) * 1000;
    for (;;) {
        await pass();
        await new Promise(r => setTimeout(r, interval));
    }
})();
